### ISSUE TITLE
issue with running on Azure

### ISSUE THREAD

**Issue by krupers** [microsoft/computerscience#109]
On my lab many students have problem with running Jupyter workbook having an issue:

"/home/mmlspark/lib/conda/envs/azureml_fe7155b29abe02ff488ec064c24fe4ae/lib/python3.5/urllib/request.py", line 1324, in unknown_open raise URLError('unknown url type: %s' % type) urllib.error.URLError: <urlopen error unknown url type: http\\>

Anyone knows how to solve it or fix it? I tried to change mmlspark, change version, add repplacements to a code, but nothing happens. Even I made myself whole environment from the beginning. Nothing :(

Case: Neural Networks - CNTK (Use the MNIST database  to train a neural network built with the Microsoft Cognitive Toolkit  and Azure Machine Learning Workbench to recognize handwritten digits.  Then deploy the model and write a Node.js app to visualize the output.)

**Comment by jeffprosise** [comment]
I will look into it and provide a fix. Thanks!

**Comment by krupers** [comment]
Thank you for quick reply and info! I will be thankful and waiting :) Cheers!

**Comment by shanamatthews** [comment]
This lab is being migrated to docs.microsoft.com/learn and won't be updated on this repo anymore, so I'm closing this issue.
