### ISSUE TITLE
JupyterHub asking for a password

### ISSUE THREAD

**Issue by krupers** [Microsoft/computerscience#110]
I got an information that students have done all deployments as in a tutorial and have issue after logging via X2Go live session. Starting JupyterHub starts browser but need to be logged in. Any of the passwords works. I tried to re-deploy it and issue still works - even "hardcode" of a password not helps in that situations.

Case: Machine Learning - Python (Create a Data Science Virtual Machine DSVM), import a  dataset containing on-time arrival information for a major U.S. airline,  and use scikit-learn to build a machine-learning model that predicts  whether flights will arrive on time.)

**Comment by jeffprosise** [comment]
I will look into it and see if i can replicate the issue.

**Comment by krupers** [comment]
I will be grateful, because it looks like - Azure staff changed something and forget to inform about :)

**Comment by krupers** [comment]
YES... Immediately I run it, in a browser I see only login or login/password what is not described in a Lab.

**Comment by jeffprosise** [comment]
Can you send a screen shot? I am not getting prompted for a login of any sort.

**Comment by shanamatthews** [comment]
I also can't repro this in this scenario, but have had similar issues when Jupyter was incorrectly configured. 
Check out [this documentation](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html) and [this StackOverflow question](https://stackoverflow.com/questions/36312372/change-jupyter-notebook-server-password) - hopefully they'll get this sorted.
Feel free to reopen if you think this is an issue with the DSVM or the lab itself 😄
