### ISSUE TITLE
Building a Chat Bot with the Azure Bot Service L Change to the tutorial

### ISSUE THREAD

**Issue by nyshthefantastic** [Microsoft/computerscience#111]
in the md file of Building a Chat Bot with the Azure Bot Service QnA Maker Preview portal is used but QnA Maker Preview portal does not accept new registrations therefore we have to go through QnA maker portal. In QnA Maker portal the steps of creating a new service is slightly different.

**Comment by jeffprosise** [comment]
Thanks for the heads up! Will update the lab this week.

**Comment by jeffprosise** [comment]
This lab has been updated for the GA release of QnA Maker.

**Comment by nyshthefantastic** [comment]
Thanks
