### ISSUE TITLE
Issues with Cognitive Toolkit Lab - Images Not Displaying Correctly

### ISSUE THREAD

**Issue by leestott** [microsoft/computerscience#112]
Please see comprehensive bug report

The situation when the bug occurs
Windows 10 64-bit
Python 3.5.2 installed.
Anaconda was not installed, so it has been installed during the execution of the install.bat from the cntk folder  downloaded from https://cntk.ai/dlwc-2.5.1.html

As you can see in the attached doc within the zip, if I launch the CNTK Python environment before the execution of images2cntk.py, the images are converted wrongly. To visualise this effect. I have executed cntk2images.py, and the result is the image files shown on the bottom window of the above screenshot.

[bug_report.zip](https://github.com/Microsoft/computerscience/files/2076668/bug_report.zip)

**Comment by jeffprosise** [comment]
I will look into it. Thanks!

**Comment by shanamatthews** [comment]
This lab is being migrated to docs.microsoft.com/learn and won't be updated on this repo anymore, so I'm closing this issue.
