### ISSUE TITLE
Add new section for online learning resources 

### ISSUE THREAD

**Issue by leestott** [microsoft/computerscience#114]
IOT School - https://iotschool.microsoft.com/ 
AI School - https://aischool.microsoft.com/
AI Labs - https://www.ailab.microsoft.com/
MVA - https://mva.microsoft.com/
Channel9 - https://channel9.msdn.com/

**Comment by gutocosta** [comment]
> @leestott
> 
> Hello!
> 
> Can I try to solve this issue?
> 
> Can I put links in this section or create another? // https://github.com/Microsoft/computerscience#content-from-other-sources

Ping @justgar
