### ISSUE TITLE
Add New Section on CaseStudies 

### ISSUE THREAD

**Issue by leestott** [microsoft/computerscience#116]
We ideally new a new section of the repo to hold casestudies from institutions using/creating/contributing to these resources and how they are using cloud within Teaching and Learning.

**Comment by irwinwilliams** [comment]
Yep, I feel like that's what I was going for with this, https://github.com/Microsoft/computerscience/issues/51

**Comment by shanamatthews** [comment]
Again, feel free to make a PR!
