### ISSUE TITLE
Hey, why not create a .MD for researchers

### ISSUE THREAD

**Issue by irwinwilliams** [Microsoft/computerscience#117]
So hey, I see @jeffprosise updates both this repo and [this one](https://github.com/MSRConnections/Azure-training-course).
Why not create a markdown file that links to all the relevant content for researchers in this repo?

**Comment by DarthOstrich** [comment]
I can do this, if you want

**Comment by Vishal-V** [comment]
Have created one and have gone by the general template. Time for a merge

**Comment by shanamatthews** [comment]
Hey, I think this is a good idea, but the research md just had one item in it. If people want to put together something a little more full-fledged, feel free!
