### ISSUE TITLE
Encyclopedia entity not showing up

### ISSUE THREAD

**Issue by Rulesvan** [microsoft/computerscience#120]
The pre-built encyclopedia entity isn't showing up to choose. What can we do?

**Comment by jeffprosise** [comment]
We will need to review the lab and see what has changed. We do regular sweeps through the content, but it is still a challenge to keep up.

**Comment by jeffprosise** [comment]
So it appears that the prebuilt encyclopedia entity has been removed:

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-deprecated

We will need to rewrite the lab, or at least do a heavy revision.

**Comment by shanamatthews** [comment]
You can find a great LUIS lab here: https://docs.microsoft.com/en-us/learn/modules/create-and-publish-a-luis-model/ 
We are deprecating the lab found on this repo in favor of Microsoft Learn.
