### ISSUE TITLE
Issue with Complimentary Course Content/Module4 - one hive command causes error.

### ISSUE THREAD

**Issue by QianyangPeng** [microsoft/computerscience#146]
The situation when the bug occurs:
After following the guide to create a HDInsight cluster.

In Data Analysis using Hadoop: Module 4, Lesson 6  Hive CLI and Hive View Hands-On Lab, we are required to run the following commands in hive CLI:
`hive> set;`
`hive> set -v;`
`hive> set env:HOME;`
`hive> set hive.cli.print.header=true;`
`hive> set hivevar:platform=Android;`

All commands except one are working fine. When running `set env:HOME;`, it shows:
env:Home is undefined as an environmental variable
Query returned non-zero code: 1, cause: null

**Comment by shanamatthews** [comment]
We're going to deprecate this content, please check out these resources on HDI for more tutorials: https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/submit-apache-hadoop-jobs-programmatically
