### ISSUE TITLE
Use Private Repos whenever Private API Keys are used

### ISSUE THREAD

**Issue by berndverst** [microsoft/computerscience#174]
All guides like this one can be updated to use Private repos now that those are free for everyone. This protects private API keys!

https://github.com/Microsoft/computerscience/blob/master/Labs/Web%20Development/Azure%20Web%20Apps%20and%20GitHub/Deploying%20a%20Cognitive%20Services%20Web%20Site%20to%20Azure%20via%20GitHub.md

Steps:

1. Create a new private repo -- leave it empty.
2. On next screen choose **import** and enter the GIT clone URL of the repo you would have forked.

Now you are using a private repo to which you can safely commit your API credentials (even though this isn't a best practice, at least no bad actor can use the API keys)

**Comment by berndverst** [comment]
@shanamatthews something I thought of while going through the tutorial, now that we have free private repos on GitHub!

**Comment by shanamatthews** [comment]
We're actually moving these Labs all to Learn, so probably won't update this here, but it's a great idea!
