### ISSUE TITLE
Should there be a strong/er link with Azure Architecture?

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/computerscience#176]
I saw @timheuer on Twitter [mention ](https://twitter.com/timheuer/status/1089952834596925440?s=09) the [Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/?WT.mc_id=docs-twitter-istarr). I believe there should be a clear relationship between the fundamentals explored here and the patterns expressed over there.

Whenever I'm conducting cloud courses, I like to show real-world practices at some point in the course, and I think this approach would help.

**Comment by shanamatthews** [comment]
This is a great idea. We will add a link!
