### ISSUE TITLE
What happens if a resource fails? Azure QnA Bot

### ISSUE THREAD

**Issue by sguthals** [microsoft/computerscience#177]
I'm following the following lab: https://github.com/Microsoft/computerscience/blob/master/Labs/AI%20and%20Machine%20Learning/Azure%20Bot%20Service/Azure%20Bot%20Service.md

And on the step "Creating a QnA Service" I actually get a failure:
<img width="1589" alt="screen shot 2019-02-25 at 6 31 50 pm" src="https://user-images.githubusercontent.com/1314285/53383269-e3d0ce00-392b-11e9-84d6-40430b1a0066.png">

I actually don't know how to proceed now.

1.  Do you know what this failure means?
2. Should we add in information about what to do if they run into failures?

I'm running this lab on a student account.

**Comment by shanamatthews** [comment]
Probably, but also, this has been migrated to Learn!
