### ISSUE TITLE
Link for bot services points to now-older version 3.

### ISSUE THREAD

**Issue by nurih** [microsoft/computerscience#181]
Suggest changing link to current version bot services: https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0

**Comment by shanamatthews** [comment]
Thanks @nurih - I believe you're referencing our Bot Services lab, which we're deprecating here and supporting on the Learn platform now: https://docs.microsoft.com/en-us/learn/modules/build-chat-bot-with-azure-bot-service/
