### ISSUE TITLE
Azure Kubernetes Service Lab with Minecraft Java Edition

### ISSUE THREAD

**Issue by ljw0913** [Microsoft/computerscience#189]
Hello there, may I ask if I were to follow the Azure Kubernetes Service Lab, how can I configure it to work for Minecraft Java edition? Thank you!

**Comment by jeffprosise** [comment]
Great question. I don't have a precise prescription, but I assume the container that we build in the lab would have to be modified. Perhaps there is an article out there somewhere listing Dockerfile commands for creating a Minecraft Java container.
