### ISSUE TITLE
Blob not available for lab 1 - Ingest

### ISSUE THREAD

**Issue by mdragt** [microsoft/computerscience#198]
computerscience/Labs/Deep Learning/200 - Machine Learning in Python/1 - Ingest/

https://topcs.blob.core.windows.net/public/FlightData.csv is not available anymore

**Comment by jeffprosise** [comment]
The Azure subscription was suspended. We are working on it.

**Comment by julmoser** [comment]
Also [blob for Azure Notebooks exercise](https://a4r.blob.core.windows.net/public/notebook-resources.zip) is not available anymore

**Comment by shanamatthews** [comment]
Thanks, yes - it's the same issue. Should hopefully be resolved within the next couple of days.

**Comment by jeffprosise** [comment]
It is resolved now.

**Comment by dipteshbose** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:38f84265-201e-00bf-3885-22b830000000 Time:2019-06-14T07:48:18.2499575Z
</Message>
</Error>

**Comment by AlexanderGolovinov** [comment]
Encountering the same issue Dec. 2024. Server response 

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:7690c36b-b01e-0048-1e61-54c8e4000000
Time:2024-12-22T11:04:31.0091907Z</Message></Error>
```
