### ISSUE TITLE
server in Hands-On Lab

### ISSUE THREAD

**Issue by rootsmusic** [microsoft/computerscience#209]
I received the error "unable to connect" to the server in first exercise's step #5 of the lab ["Using Microsoft Power BI to Explore and Visualize Data"](https://github.com/Microsoft/computerscience/blob/master/Labs/Big%20Data%20and%20Analytics/Power%20BI/Power%20BI.md).  The error suggested:  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.

**Comment by shanamatthews** [comment]
Thanks @rootsmusic - We're actually going to deprecate this lab - check out fresh Power BI labs on Microsoft Learn: https://docs.microsoft.com/en-us/learn/browse/?term=power%20bi
