### ISSUE TITLE
Broken links in computerscience/Educator Resources/K12/

### ISSUE THREAD

**Issue by andreas-wilm** [microsoft/computerscience#227]
Hello, the introduction to data science and introduction to AI links in computerscience/Educator Resources/K12/ are dead.
Thanks

**Comment by shanamatthews** [comment]
@sguthals - looks like you missed updating a couple of links on this page: https://github.com/microsoft/computerscience/tree/master/Educator%20Resources/K12

**Comment by jimbobbennett** [comment]
Thank you for your contribution. This repository is being overhauled, and as such a lot of out of data content will be removed. Therefore this issue will be closed.
