### ISSUE TITLE
Can't connect to Power BI Lab data warehouse

### ISSUE THREAD

**Issue by mdragt** [microsoft/computerscience#228]
I can't connect to the azure sql data warehouse anymore via power bi services. Any hint?

![power bi azure sql data warehouse issue](https://user-images.githubusercontent.com/3117770/68025458-0e3e0c80-fcad-11e9-85dd-a52accb904c4.png)

**Comment by jimbobbennett** [comment]
Thank you for your contribution. This repository is being overhauled, and as such a lot of out of data content will be removed. Therefore this issue will be closed.
