### ISSUE TITLE
Operation returned an invalid status code&#39 (Azure Storage and Cognitive Services )

### ISSUE THREAD

**Issue by Hideginyo** [microsoft/computerscience#234]
Thank you for your good lecture on "Azure Storage and Cognitive Services"
I have already tried several times to rebuild it along with instructions.

Every time I encounter the "Operation returned an invalid status code &#39; NotFound&#39;" on "Exercise 5: Use Cognitive Services to generate metadata".

I'm a novice in this field. If this is not suitable for this site, sorry. 

![question](https://user-images.githubusercontent.com/44321888/69491408-40bbdd80-0ed8-11ea-8cd6-b94457bd6b6c.PNG)

**Comment by jeffprosise** [comment]
In Exercise 5, Step 8, try NOT adding "/vision/v1.0" to the endpoint URL. It shouldn't be necessary with the Computer Vision NuGet package.

**Comment by Hideginyo** [comment]
Thank you for your reply I move forward!!!!! doing well!!
