### ISSUE TITLE
issue about Docker in Part 2 Exerice 1

### ISSUE THREAD

**Issue by cheahengsoon** [Microsoft/computerscience#58]
300 - Neural Networks with CNTK Part 2 Exercise 1
The Docker refer to Docker Enterprise version or Community Version.
and 
When I try to upload the convert.py to Docker it shown Not Responding

**Comment by shanamatthews** [comment]
Hey @cheahengsoon - it's referring to the free community version (Docker Desktop).
I'll take a look at trying to repro your issue once I'm on my other machine ❇️
