### ISSUE TITLE
Looking forward with Tensorflow lab

### ISSUE THREAD

**Issue by cheahengsoon** [Microsoft/computerscience#97]
Looking forward with Tensorflow lab

**Comment by jeffprosise** [comment]
I have an early draft in my hands but am traveling overseas this week and next. It WILL be ready soon...promise!

Sent from my iPhone

On Apr 9, 2018, at 4:21 AM, Shana Matthews <notifications@github.com<mailto:notifications@github.com>> wrote:


Me too! It's a little delayed, but hopefully we should have something to show you either this week or next :)
